# Generated by Django 5.2.17 on 2026-09-21 14:26

import submissions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=submissions.models.submission_file_path),
        ),
        migrations.AddField(
            model_name='submission',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='submission',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('LATE', 'Late'), ('REVIEWED', 'Reviewed')], default='SUBMITTED', max_length=20),
        ),
    ]
