# Generated by Django 5.2.17 on 2026-09-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_submission_file_submission_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='feedback',
            field=models.TextField(blank=True, verbose_name='Faculty Feedback'),
        ),
        migrations.AddField(
            model_name='submission',
            name='marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Marks Awarded'),
        ),
        migrations.AddField(
            model_name='submission',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At'),
        ),
    ]
