# Generated by Django 5.2.17 on 2026-09-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='max_marks',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=6, verbose_name='Maximum Marks'),
        ),
    ]
