# Generated by Django 5.2.17 on 2026-09-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_assignment_max_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='reference_file',
            field=models.FileField(blank=True, null=True, upload_to='assignment_references/'),
        ),
    ]
